CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`store_name` varchar(255) NOT NULL,
	`area` varchar(255) NOT NULL,
	`business_type` enum('restaurant','salon') NOT NULL,
	`business_subtype` varchar(100),
	`slug` varchar(255) NOT NULL,
	`status` varchar(50) NOT NULL DEFAULT 'NEW_LEAD',
	`google_maps_url` text,
	`current_website_url` text,
	`instagram_url` text,
	`email` varchar(320),
	`whatsapp_number` varchar(50),
	`phone_number` varchar(50),
	`logo_url` text,
	`photo_urls` json,
	`screenshot_urls` json,
	`source_photos` json,
	`notes` text,
	`template` varchar(100),
	`ambiance_lighting` varchar(50),
	`ambiance_surfaces` varchar(50),
	`ambiance_color_palette` varchar(50),
	`ambiance_mood` varchar(50),
	`ambiance_time_of_day` varchar(50),
	`palette_accent` varchar(20),
	`hero_tagline` varchar(500),
	`hero_subtitle` text,
	`story_paragraphs` json,
	`menu_items` json,
	`gallery_images` json,
	`info_address` text,
	`info_hours` text,
	`info_phone` varchar(50),
	`info_reservation_url` text,
	`video_url` text,
	`video_task_id` varchar(255),
	`video_cost_usd` varchar(20),
	`frames_path_landscape` text,
	`frame_count_landscape` int,
	`frames_path_portrait` text,
	`frame_count_portrait` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`),
	CONSTRAINT `leads_slug_unique` UNIQUE(`slug`)
);
